### ISSUE TITLE
ImportError: cannot import name OctConv2d

### ISSUE THREAD

**Issue by tx1994108** [braincreators/octconv#1]
Thank you for your open source, but I have a problem.

 from octconv import OctConv2d
ImportError: cannot import name OctConv2d

**Comment by miguelvr** [comment]
How did you install the repo?

**Comment by tx1994108** [comment]
> How did you install the repo?

I followed your instructions.

pip install octconv
pip install git+https://github.com/braincreators/octconv.git#egg=octconv

**Comment by miguelvr** [comment]
are you running on a conda / virtualenv?

just install with 
`pip install octconv`
