### ISSUE TITLE
i ues OctCon2d repalce Conv2d in nn.Sequential,but come erro

### ISSUE THREAD

**Issue by daixiangzi** [braincreators/octconv#6]
about code:
nn.Sequential(#nn.Conv2d(inp, oup, 3, stride, 1, bias=False),OctConv2d(in_channels=inp,out_channels=oup,kernel_size=3,stride=stride,padding=1,alpha=0.5))

erro:
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by xingchen77** [comment]
me  too
